name: 'betflow'
version: '1.0.0'
config-version: 2

profile: 'betflow'

model-paths: ["dbt/models"]
test-paths: ["dbt/tests"]
macro-paths: ["dbt/macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  betflow:
    staging:
      games:
        +materialized: view
        +schema: staging
      odds:
        +materialized: view
        +schema: staging
    marts:
      +materialized: table
      +schema: analytics