version: 2.1

# Import required orbs
orbs:
  aws-cli: circleci/aws-cli@5.1.1
  terraform: circleci/terraform@3.3

# Setup workflow orchestration
setup: true

workflows:
  infrastructure_deployment:
    jobs:
      - vpc_provisioning:
          context:
            - aws-oidc-context
            - terraform-context
#      - ec2_provisioning:
#          context:
#            - aws-oidc-context
#            - terraform-context

# Use continuation to generate workflows
jobs:
  vpc_provisioning:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - run:
          command: |
            cd .circleci/infrastructure_deployment
            circleci config pack vpc_provisioning.yml > processed_config.yml
      - persist_to_workspace:
          root: .circleci/infrastructure_deployment
          paths:
            - processed_config.yml


