version: 2.1

setup: true # for CIRCLE_CONTINUATION_KEY

orbs:
  path-filtering: circleci/path-filtering@1.1.0

parameters:
  run_workflow:
    type: string
    default: ""

workflows:
  version: 2
  path-filtering:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            terraform/vpc/.* run_workflow "vpc"
            .circleci/infrastructure_deployment/vpc* run_workflow "vpc"
            terraform/subnets/.* run_workflow "subnets"
            .circleci/infrastructure_deployment/subnets* run_workflow "subnets"
            terraform/ec2/.* run_workflow "ec2"
            .circleci/infrastructure_deployment/ec2* run_workflow "ec2"
          base-revision: main
          config-path: .circleci/continue_config.yml
          filters:
            branches:
              only:
                - dev
                - main