version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0

parameters:
  run-vpc-workflow:
    type: boolean
    default: false

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            terraform/vpc/.* run-vpc-workflow true
            .circleci/infrastructure_deployment/.* run-vpc-workflow true
          base-revision: dev
          config-path: .circleci/infrastructure_deployment/vpc_provisioning.yml
          filters:
            branches:
              only:
                - dev