version: 2.1

setup: true # for CIRCLE_CONTINUATION_KEY

orbs:
  path-filtering: circleci/path-filtering@1.1.0

parameters:
  run_vpc:
    type: boolean
    default: false
  run_subnets:
    type: boolean
    default: false
  run_ec2:
    type: boolean
    default: false

jobs:
  pass-continuation:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Store continuation key
          command: |
            echo "export CIRCLE_CONTINUATION_KEY=${CIRCLE_CONTINUATION_KEY}" >> $BASH_ENV
            source $BASH_ENV

workflows:
  version: 2
  path-filtering:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            terraform/vpc/.* run_vpc true
            .circleci/infrastructure_deployment/vpc* run_vpc true
            terraform/subnets/.* run_subnets true
            .circleci/infrastructure_deployment/subnets* run_subnets true
            terraform/ec2/.* run_ec2 true
            .circleci/infrastructure_deployment/ec2* run_ec2 true
          base-revision: main
          config-path: .circleci/continue_config.yml
          post-steps:
            - pass-continuation
          filters:
            branches:
              only:
                - dev
                - main