version: 2.1

# Import all workflow configurations
setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            terraform/vpc/.* run-vpc-workflow true
            .circleci/infrastructure_deployment/.* run-vpc-workflow true
          base-revision: main
          config-path: .circleci/infrastructure_deployment/vpc_workflow.yml
          filters:
            branches:
              only:
                - main
                - dev