version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0
  continuation: circleci/continuation@0.2.0

parameters:
  deploy_vpc:
    type: boolean
    default: false
  deploy_ec2:
    type: boolean
    default: false
  deploy_security_group:
    type: boolean
    default: false

workflows:
  version: 2
  manage-infrastructure:
    jobs:
      - path-filtering/filter:
          name: check-vpc-changes
          mapping: |
            terraform/vpc/.* deploy_vpc true
#            .circleci/infrastructure_deployment/vpc/.* deploy_vpc true
          base-revision: main
          config-path: .circleci/infrastructure_deployment/vpc/vpc_workflow.yml
          filters:
            branches:
              only:
                - dev
                - main

      - path-filtering/filter:
          name: check-ec2-changes
          mapping: |
            terraform/ec2/.* deploy_ec2 true
          base-revision: main
          config-path: .circleci/infrastructure_deployment/ec2/ec2_workflow.yml
          filters:
            branches:
              only:
                - dev
                - main

      - path-filtering/filter:
          name: check-security-group-changes
          mapping: |
            terraform/security_group/.* deploy_security_group true
          base-revision: main
          config-path: .circleci/infrastructure_deployment/security_group/sg_workflow.yml
          filters:
            branches:
              only:
                - dev
                - main