version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  terraform: circleci/terraform@3.3

jobs:
  deploy_vpc:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${AWS_FEDERATED_USER_ROLE}
          aws-region: ${AWS_REGION}  # Note the double quotes
          profile-name: "oidc-profile"  # Optional but recommended
          role-session-name: "circleci-vpc-deployment"  # Optional but recommended
          session-duration: "3600"  # Optional, duration in seconds
      - run:
          name: Debug AWS Authentication
          command: |
            aws sts get-caller-identity --profile oidc-profile
      - terraform/install:
          terraform_version: "1.5.0"
      - run:
          name: Initialize and Plan
          command: |
            cd terraform/vpc
            export AWS_PROFILE=oidc-profile
            export TF_LOG=DEBUG
            terraform init \
              -backend-config="bucket=${TF_STATE_BUCKET}" \
              -backend-config="region=${AWS_REGION}" \
              -backend-config="dynamodb_table=${TF_LOCK_TABLE}"
            terraform plan -out=tfplan
      - run:
          name: Apply Changes
          command: |
            cd terraform/vpc
            export AWS_PROFILE=oidc-profile
            terraform apply -auto-approve tfplan

workflows:
  deploy_infrastructure:
    jobs:
      - deploy_vpc:
          context: aeb_secrets
          filters:
            branches:
              only:
                - dev