version: 2.1

setup: true # for CIRCLE_CONTINUATION_KEY

orbs:
  path-filtering: circleci/path-filtering@1.1.0

parameters:
  run_vpc:
    type: boolean
    default: false
  run_subnets:
    type: boolean
    default: false
  run_ec2:
    type: boolean
    default: false

workflows:
  version: 2
  path-filtering:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          mapping: |
            terraform/vpc/.* run_workflow true
            .circleci/infrastructure_deployment/vpc* run_workflow true
            terraform/subnets/.* run_workflow true
            .circleci/infrastructure_deployment/subnets* run_workflow true
            terraform/ec2/.* run_workflow true
            .circleci/infrastructure_deployment/ec2* run_workflow true
          base-revision: main
          config-path: .circleci/continue_config.yml
          filters:
            branches:
              only:
                - dev
                - main