version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0
  continuation: circleci/continuation@0.2.0

parameters:
  deploy_vpc:
    type: boolean
    default: false
  deploy_subnets:
    type: boolean
    default: false
  deploy_ec2:
    type: boolean
    default: false

workflows:
  version: 2
  manage-infrastructure:
    unless: << pipeline.parameters.deploy_vpc >>  # Only run path filtering if not triggered directly
    jobs:
      - path-filtering/filter:
          name: check-vpc-changes
          mapping: |
            terraform/vpc/* deploy_vpc true
            .circleci/infrastructure_deployment/vpc* deploy_vpc true
          base-revision: main
          config-path: .circleci/infrastructure_deployment/vpc_workflow.yml
          filters:
            branches:
              only:
                - dev
                - main

      - path-filtering/filter:
          name: check-changes
          mapping: |
            terraform/vpc/* deploy_subnets true
            .circleci/infrastructure_deployment/subnets* deploy_subnets true
          base-revision: dev
          config-path: .circleci/infrastructure_deployment/subnets_workflow.yml
          filters:
            branches:
              only:
                - dev
                - main

#      - path-filtering/filter:
#          name: check-ec2-changes
#          mapping: |
#            terraform/ec2/* deploy_ec2 true
#            .circleci/infrastructure_deployment/ec2* deploy_ec2 true
#          base-revision: main
#          config-path: .circleci/infrastructure_deployment/ec2_workflow.yml
#          filters:
#            branches:
#              only:
#                - dev
#                - main
  trigger-vpc:
    when: << pipeline.parameters.deploy_vpc >>  # Run this workflow when deploy_vpc is true
    jobs:
      - continuation/continue:
          configuration_path: .circleci/infrastructure_deployment/vpc_workflow.yml

  trigger-subnets:
    when: << pipeline.parameters.deploy_subnets >>
    jobs:
      - continuation/continue:
          configuration_path: .circleci/infrastructure_deployment/subnet_workflow.yml

#  trigger-ec2:
#    when: << pipeline.parameters.deploy_ec2 >>
#    jobs:
#      - continuation/continue:
#          configuration_path: .circleci/infrastructure_deployment/ec2_workflow.yml


