version: 2.1

#setup: true # for CIRCLE_CONTINUATION_KEY

orbs:
  continuation: circleci/continuation@0.2.0

parameters:
  run_workflow:
    type: string
    default: ""

jobs:
  debug_job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Debug Continuation Key
          command: |
            echo "Continuation Key: $CIRCLE_CONTINUATION_KEY"
            echo "Run Workflow: << pipeline.parameters.run_workflow >>"

workflows:
  continue-workflow:
    when:
      not:
        equal: [ "", << pipeline.parameters.run_workflow >> ]
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/infrastructure_deployment/<< pipeline.parameters.run_workflow >>_workflow.yml"