version: 2.1

parameters:
  run_vpc:
    type: boolean
    default: false
  run_subnets:
    type: boolean
    default: false
  run_ec2:
    type: boolean
    default: false

orbs:
  continuation: circleci/continuation@1.0.0

workflows:
  version: 2
  trigger-vpc-workflow:
    when:
      equal: [ true, << pipeline.parameters.run_vpc >> ]
    jobs:
      - continuation/continue:
          name: vpc-workflow
          configuration_path: .circleci/infrastructure_deployment/vpc/vpc_workflow.yml

  trigger-subnets-workflow:
    when:
      equal: [ true, << pipeline.parameters.run_subnets >> ]
    jobs:
      - continuation/continue:
          name: subnet-workflow
          configuration_path: .circleci/infrastructure_deployment/subnets/subnets_workflow.yml

  trigger-ec2-workflow:
    when:
      equal: [ true, << pipeline.parameters.run_ec2 >> ]
    jobs:
      - continuation/continue:
          name: ec2-workflow
          configuration_path: .circleci/infrastructure_deployment/ec2/ec2_workflow.yml