version: 2.1

orbs:
  continuation: circleci/continuation@1.0.0

parameters:
  run_workflow:
    type: string
    default: ""

workflows:
  continue-workflow:
    when:
      not:
        equal: [ "", << pipeline.parameters.run_workflow >> ]
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/infrastructure_deployment/<< pipeline.parameters.run_workflow >>_workflow.yml"