version: 2.1

parameters:
  run_vpc:
    type: boolean
    default: false
  run_subnets:
    type: boolean
    default: false
  run_ec2:
    type: boolean
    default: false

orbs:
  continuation: circleci/continuation@1.0.0


jobs:
  trigger_workflow:
    docker:
      - image: cimg/base:stable
    parameters:
      workflow_path:
        type: string
    steps:
      - continuation/continue:
          configuration_path: << parameters.workflow_path >>

workflows:
  version: 2
  trigger-workflows:
    jobs:
      - trigger_workflow:
          name: vpc-workflow
          workflow_path: .circleci/infrastructure_deployment/vpc_workflow.yml
          requires:
            - approval
          when:
            equal: [ true, << pipeline.parameters.run_vpc >> ]

      - trigger_workflow:
          name: subnet-workflow
          workflow_path: .circleci/infrastructure_deployment/subnets_workflow.yml
          requires:
            - approval
          when:
            equal: [ true, << pipeline.parameters.run_subnets >> ]

      - trigger_workflow:
          name: ec2-workflow
          workflow_path: .circleci/infrastructure_deployment/ec2_workflow.yml
          requires:
            - approval
          when:
            equal: [ true, << pipeline.parameters.run_ec2 >> ]

      - approval:
          type: approval