#dynamic configuration multi-path filtering
version: 2.1

setup: true # for CIRCLE_CONTINUATION_KEY

#parameters:
#  run_vpc:
#    type: boolean
#    default: false
#  run_subnets:
#    type: boolean
#    default: false
#  run_ec2:
#    type: boolean
#    default: false
parameters:
  run_workflow:
    type: string
    default: ""

orbs:
  continuation: circleci/continuation@0.2.0

workflows:
  version: 2
  continue-workflow:
    when:
      not:
        equal: [ "", << pipeline.parameters.run_workflow >> ]
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/infrastructure_deployment/<< pipeline.parameters.run_workflow >>_workflow.yml"

#  trigger-workflows:
#    jobs:
#      - continuation/continue:
#          name: vpc-workflow
#          configuration_path: .circleci/infrastructure_deployment/vpc/vpc_workflow.yml
#          when: << pipeline.parameters.run_vpc >>
#      - continuation/continue:
#          name: subnet-workflow
#          configuration_path: .circleci/infrastructure_deployment/subnets/subnets_workflow.yml
#          when: << pipeline.parameters.run_subnets >>
#      - continuation/continue:
#          name: ec2-workflow
#          configuration_path: .circleci/infrastructure_deployment/ec2/ec2_workflow.yml
#          when: << pipeline.parameters.run_ec2 >>