-- Create main database
CREATE DATABASE IF NOT EXISTS SPORTS_DB;

-- Create schemas for layered architecture
CREATE SCHEMA IF NOT EXISTS SPORTS_DB.RAW_LAYER;
CREATE SCHEMA IF NOT EXISTS SPORTS_DB.SILVER_LAYER;
CREATE SCHEMA IF NOT EXISTS SPORTS_DB.GOLD_LAYER;