CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NBA_GAMES (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NBA_GAMES_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NBA_ODDS (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NBA_ODDS_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NHL_GAMES (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NHL_GAMES_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NHL_ODDS (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NHL_ODDS_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NFL_GAMES (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NFL_GAMES_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NFL_ODDS (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NFL_ODDS_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.CFB_GAMES (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.CFB_GAMES_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.CFB_ODDS (
    DATA VARIANT AS (parse_json($1))
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.CFB_ODDS_STAGE
FILE_FORMAT = SPORTS_DB.RAW_LAYER.PARQUET_FORMAT
AUTO_REFRESH = TRUE;