CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NBA_GAMES (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NBA_GAMES_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NBA_ODDS (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NBA_ODDS_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NHL_GAMES (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NHL_GAMES_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NHL_ODDS (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NHL_ODDS_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NFL_GAMES (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NFL_GAMES_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.NFL_ODDS (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.NFL_ODDS_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.CFB_GAMES (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.CFB_GAMES_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;


CREATE OR REPLACE EXTERNAL TABLE SPORTS_DB.RAW_LAYER.CFB_ODDS (
    DATA VARIANT AS (VALUE:$1),
    FILE_NAME VARCHAR AS METADATA$FILENAME,
    LAST_MODIFIED TIMESTAMP_NTZ AS METADATA$FILE_LAST_MODIFIED
)
WITH LOCATION = @SPORTS_DB.RAW_LAYER.CFB_ODDS_STAGE
PATTERN = '.*[.]parquet'
FILE_FORMAT = (
    TYPE = PARQUET
    REPLACE_INVALID_CHARACTERS = TRUE
)
AUTO_REFRESH = TRUE;