version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  terraform: circleci/terraform@3.3
  continuation: circleci/continuation@0.2.0

jobs:
  ec2_provision:
    docker:
      - image: cimg/aws:2024.03   # base to aws
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OIDC_ROLE}
          aws-region: AWS_REGION
          profile-name: oidc-profile
      - terraform/install:
          terraform_version: "1.5.0"
      - run:
          name: Initialize EC2 Terraform
          command: |
            cd terraform/ec2
            terraform init \
              -backend-config="bucket=${TF_STATE_BUCKET}" \
              -backend-config="region=${AWS_REGION}" \
              -backend-config="dynamodb_table=${TF_LOCK_TABLE}"
      - run:
          name: Plan EC2 Changes
          command: |
            cd terraform/ec2
            terraform plan \
              -var="vpc_id=${KAFKA_VPC_ID}" \
              -var="subnet_id=${SUBNET_ID}" \
              -var="key_pair_name=${OLD_KEY_PAIR}" \
              -var='instance_type=t3a.medium" \
              -var="iam_role_name=${EC2_IAM_ROLE}" \
              -var="vpc_cidr=${VPC_CIDR}" \
              -var="allowed_cidr_blocks=${ALLOWED_CIDRS}" \
              -out=tfplan

  terraform-apply:
    docker:
      - image: cimg/base:2024.01
    steps:
      - checkout
      - assume-role-with-oidc
      - terraform/install:
          terraform_version: "1.5.0"
      - run:
          name: Apply Terraform Changes
          command: |
            cd terraform/ec2
            terraform apply tfplan

workflows:
  infrastructure_deployment:
    jobs:
      - terraform-plan:
          context:
            - aws-oidc-context
            - terraform-context
      - approve-apply:
          type: approval
          requires:
            - terraform-plan
      - terraform-apply:
          requires:
            - approve-apply
          context:
            - aws-oidc-context
            - terraform-context