version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  terraform: circleci/terraform@3.3

jobs:
  subnet_provision:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OIDC_ROLE}
          aws-region: AWS_REGION
          profile-name: oidc-profile
      - terraform/install:
          terraform_version: "1.5.0"
      - run:
          name: Initialize Terraform
          command: |
            cd terraform/subnets
            export AWS_PROFILE=oidc-profile
            terraform init \
              -backend-config="bucket=${TF_STATE_BUCKET}" \
              -backend-config="region=${AWS_REGION}" \
              -backend-config="dynamodb_table=${TF_LOCK_TABLE}"
      - run:
          name: Plan Subnet Changes
          command: |
            cd terraform/subnets
            export AWS_PROFILE=oidc-profile
            terraform plan \
              -var="vpc_id=${KAFKA_VPC_ID}" \
              -var="environment=production" \
              -out=subnet_tfplan
      - persist_to_workspace:
          root: .
          paths:
            - terraform/subnets/subnet_tfplan
      - run:
          name: Apply Subnet Changes
          command: |
            cd terraform/subnets
            export AWS_PROFILE=oidc-profile
            terraform apply -auto-approve subnet_tfplan

workflows:
  deploy_subnets:
    jobs:
      - subnet_provision:
          context: aeb_secrets
          filters:
            branches:
              only:
                - dev
                - main