version: 2

models:
  - name: stg_nba_odds
    description: Staged NBA betting odds data
    columns:
      - name: game_id
        description: Unique identifier for each game
        tests:
          - not_null
      - name: sport_key
        description: Sport identifier
        tests:
          - not_null
          - accepted_values:
              values: ['basketball_nba']
      - name: home_price
        description: Betting price for home team
        tests:
          - not_null
      - name: away_price
        description: Betting price for away team
        tests:
          - not_null
      - name: bookmaker_key
        description: Unique identifier for bookmaker
        tests:
          - not_null
      - name: commence_time
        description: Game start time
        tests:
          - not_null

  - name: stg_nfl_odds
    description: Staged NFL betting odds data
    columns: &sports_odds_columns
      - name: game_id
        tests:
          - not_null
      - name: sport_key
        tests:
          - not_null
          - accepted_values:
              values: ['americanfootball_nfl']
      - name: home_price
        tests:
          - not_null
      - name: away_price
        tests:
          - not_null
      - name: bookmaker_key
        tests:
          - not_null
      - name: commence_time
        tests:
          - not_null

  - name: stg_nhl_odds
    description: Staged NHL betting odds data
    columns: *sports_odds_columns

  - name: stg_cfb_odds
    description: Staged College Football betting odds data
    columns: *sports_odds_columns