version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  terraform: circleci/terraform@3.3
  continuation: circleci/continuation@0.2.0

jobs:
  vpc_provision:
    docker:
      - image: cimg/aws:2024.03
    steps:
      - checkout
      - aws-cli/setup:
          role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${OIDC_ROLE}
          aws-region: AWS_REGION
          profile-name: oidc-profile
      - terraform/install:
          terraform_version: "1.5.0"
      - run:
          name: Initialize VPC Terraform
          command: |
            cd terraform/vpc
            export AWS_PROFILE=oidc-profile
            terraform init \
              -backend-config="bucket=${TF_STATE_BUCKET}" \
              -backend-config="region=${AWS_REGION}" \
              -backend-config="dynamodb_table=${TF_LOCK_TABLE}"
      - run:
          name: Plan VPC Changes
          command: |
            cd terraform/vpc
            export AWS_PROFILE=oidc-profile
            terraform plan \
              -var="aws_region=${AWS_REGION}" \
              -var="vpc_cidr=10.0.0.0/16" \
              -var="environment=production" \
              -out=vpc_tfplan
      - run:
          name: Apply VPC Changes
          command: |
            cd terraform/vpc
            export AWS_PROFILE=oidc-profile
            terraform apply -auto-approve vpc_tfplan
      - run:
          name: Validate VPC Resources
          command: |
            cd terraform/vpc
            terraform show
            terraform state list

workflows:
  version: 2
  deploy_vpc:
#    when:
#      equal: [ true, << pipeline.parameters.deploy_vpc >> ]
    jobs:
      - vpc_provision:
          context: aeb_secrets
          filters:
            branches:
              only:
                - dev
                - main