name: Type Checking

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]

jobs:
  mypy-type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install .
          pip install mypy
          python3 -m pip install types-requests
          python3 -m pip install types-PyYAML

      - name: Run MyPy
        run: |
          mypy src/
#          mypy airflow_dags/custom_operators.py
#          mypy airflow_dags/dag_assets.py
